apiVersion: v1
kind: Pod
metadata:
  name: service-test
  labels:
    app: service-test
spec:
  containers:
    - name: service-test
      image: dsgrilo/service-grilo:latest
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  